# text_sizes
FONT = "Calibri"
INPUT_FONT_SIZE = 23
TABLE_HEADING_FONT_SIZE = 16
SAVE_PATH_FONT_SIZE = 15
BUTTON_CORNER_RADIUS = 6

# colors
GREEN = "#50BFAB"
DARK_GREEN = "#3A8A7B"
WHITE = "#F2F2F2"
BLACK = "#1F1F1F"
LIGHT_GRAY = "#E8E8E8"
GRAY = "#D9D9D9"

# title hex
TITLE_HEX_COLOR = 0x00ABBF50

